apiVersion: 1

datasources:
  - name: Monitoring PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: example
    jsonData:
      database: monitoring
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
